### ISSUE TITLE
Stop sessions from requesting authentication

### ISSUE THREAD

**Issue by vlj91** [alces-software/clusterware-sessions#3]
On first-time connect to an Alces GNOME session as an admin user (`alces`) - the following appears: 

![screen shot 2016-02-10 at 10 25 10](https://cloud.githubusercontent.com/assets/10548294/12947044/9d6d5160-cff0-11e5-973c-47abbfc38478.png)

Appears to be fine as non-administrator users. 

Is there a way we can stop this from happening?

**Comment by vlj91** [comment]
As suggested by @mjtko: 

* Attempt to get rid of "getting started" - create `~/.config/gnome-initial-setup-done` with the contents `yes<EOF>`

**Comment by sierra-tango-echo** [comment]
historically we've also had problems with packagekit popping up to sudo users every day - we stop that with yum remove 'gnome-packagekit' - might be something worth checking for at the same time as resolving this one

**Comment by mjtko** [comment]
Yup -- packagekit is currently explicitly dealt with here: https://github.com/alces-software/clusterware-sessions/blob/master/gnome/metadata.yml#L7

**Comment by mjtko** [comment]
Appears this is cos `alces` user is in `wheel` group.

```
[root@login1(demo) 00-clusterware.d]# cat /etc/polkit-1/rules.d/50-default.rules
/* -*- mode: js; js-indent-level: 4; indent-tabs-mode: nil -*- */

// DO NOT EDIT THIS FILE, it will be overwritten on update
//
// Default rules for polkit
//
// See the polkit(8) man page for more information
// about configuring polkit.

polkit.addAdminRule(function(action, subject) {
    return ["unix-group:wheel"];
});
```

Think we can tweak this using some kind of polkit configuration.

**Comment by mjtko** [comment]
This seems to do the trick:

```
[root@login1(demo) ~]# cat /etc/polkit-1/localauthority/10-vendor.d/clusterware.pkla
[Alces Clusterware - disable create color managed device auth prompt for admins]
Identity=unix-group:wheel
Action=org.freedesktop.color-manager.create-device
ResultAny=yes
ResultInactive=yes
ResultActive=yes

[Alces Clusterware - disable network proxy auth prompt for admins]
Identity=unix-group:wheel
Action=org.freedesktop.packagekit.system-network-proxy-configure
ResultAny=yes
ResultInactive=yes
ResultActive=yes
```
